[package]
name = "sport-log-scheduler"
version = "0.1.0"
edition = "2018"

[dependencies]

sport-log-types = { path = "../sport-log-types" }

reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls", "blocking"] }
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1.0.117", features = ["derive"] }
toml = "0.5.8"