[package]
name = "sport-log-server-derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
rocket = "0.4.10"
Inflector = "0.11.4"

syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0.27"
