[workspace]
members = [
    "sport-log-server",
    "sport-log-types-derive",
    "sport-log-types",
    "sport-log-scheduler",
    "sport-log-api-tester",
    "sport-log-action-provider-sportstracker",
    "sport-log-password-hasher"
]