[workspace]
members = [
    "sport-log-server",
    "sport-log-types-derive",
    "sport-log-types",
    "sport-log-scheduler",
    "sport-log-ap-utils",
    "sport-log-action-provider-sportstracker",
    "sport-log-action-provider-wodify-login",
    "sport-log-action-provider-wodify-wod",
]