
[workspace]
#members = ["sport_log_server", "sport-log-api-tester", "sport_log_server_derive", "sport_log_action_provider_sportstracker"]
members = ["sport_log_server", "sport-log-api-tester", "sport_log_server_derive"]