[package]
name = "sport-log-types-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11"
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

[package.metadata.cargo-machete]
ignored = ["Inflector"]

[lints]
workspace = true
