[package]
name = "sport-log-server"
version = "0.1.0"
edition = "2021"
default-run = "sport-log-server"

[dependencies]
sport-log-types = { path = "../sport-log-types", features = ["server"] }

tokio = { version = "1.9", features = ["full"] }
rocket = { version = "0.5.0-rc.1", features = ["json"] }
rocket_sync_db_pools = { version = "0.1.0-rc.1", features = ["diesel_postgres_pool"] }
diesel = { version = "1.4", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "1.4"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.82"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
figment = { version = "0.10", features = ["toml"] }

[dev-dependencies]
base64 = "0.13"
rand = "0.8"
