[package]
name = "sport-log-server"
version = "0.1.0"
edition = "2018"
default-run = "sport-log-server"

[dependencies]
sport-log-server-derive = { path = "../sport-log-server-derive" }
sport-log-types = { path = "../sport-log-types" }

rocket = { version = "0.5.0-rc.1", features = ["json"] }
rocket_sync_db_pools = { version = "0.1.0-rc.1", features = ["diesel_postgres_pool"] }
diesel = { version = "1.4.4", features = ["postgres", "r2d2", "chrono"] }
diesel-derive-enum = { version = "1.1.1", features = ["postgres"] }
serde = { version = "1.0.116", features = ["derive"]}
dotenv = "0.15.0"
chrono = { version = "0.4.19", features = ["serde"] }
base64 = "0.13.0"
toml = "0.5.8"
lazy_static = "1.4.0" 