drop table cardio_session_archive;
drop index cardio_session_idx;
drop table cardio_session;
drop table cardio_blueprint;
drop table route_archive;
drop index route_idx;
drop table route;
drop type "position";
drop type cardio_type;
