name: sport_log
description: Sport Log

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.4.0+10 # also change in flatpak/org.sport_log.sport_log_client.metainfo.xml

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audio_session: ^0.1.16
  audioplayers: ^6.0.0
  awesome_notifications: ^0.8.2
  collection: ^1.16.0
  device_info_plus: ^10.1.0
  file_picker: ^8.0.0+1
  fixnum: ^1.0.0
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.7.5
  flutter_foreground_task: ^6.0.0+1
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^4.0.2
  fluttertoast: ^8.0.8
  gpx: ^2.1.1
  hive_flutter: ^1.1.0
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.4.0
  latlong2: ^0.9.0
  location: 
    # location from GPS only 
    git:
      url: https://github.com/LorenzSchueler/flutterlocation
      path: packages/location
      ref: develop
  logger: ^2.0.1
  mapbox_api: #^1.0.0
    # http 1.1
    git:
      url: https://github.com/LorenzSchueler/mapbox-api
  mapbox_maps_flutter: #^0.4.3
    # onTap Point and ScreenCoordinate
    git:
      url: https://github.com/LorenzSchueler/mapbox-maps-flutter
  mapbox_search: ^4.2.0
  open_file: ^3.3.1
  package_info_plus: ^7.0.0
  path_provider: ^2.0.10
  pedometer: #^3.0.0
    # callback for every step
    git:
      url: https://github.com/LorenzSchueler/flutter-plugins
      path: packages/pedometer
      ref: fa6072adb257648c3e45f4d10a71fe8d5f8b784b
  permission_handler: ^11.0.0
  polar: ^7.0.0
  provider: ^6.0.2
  result_type: ^0.2.0
  sqflite: ^2.0.3
  sqflite_common_ffi: ^2.1.1
  string_validator: ^1.0.2
  synchronized: ^3.0.0+3
  url_launcher: ^6.0.20
  wakelock_plus: ^1.2.2
  yaml: ^3.1.0

dependency_overrides:
  location_android: 
    # location from GPS only 
    git:
      url: https://github.com/LorenzSchueler/flutterlocation
      path: packages/location_android
      ref: develop

dev_dependencies:
  build_runner: ^2.1.0 # json
    # dart run build_runner build --delete-conflicting-outputs
  #dart_code_linter: ^1.1.2
    #git: 
    #  url: https://github.com/bancolombia/dart-code-linter
    #  ref: 8dffeffe04c7aa7f46980e416418ce41aee104a7
    # dart run dart_code_linter:metrics analyze lib
    # dart run dart_code_linter:metrics check-unnecessary-nullable lib
    # dart run dart_code_linter:metrics check-unused-files lib
    # dart run dart_code_linter:metrics check-unused-code lib
  faker: ^2.0.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.0.1 
    # dart run icons_launcher:create
  integration_test:
    sdk: flutter
  json_serializable: ^6.3.0 # json

icons_launcher:
  image_path: "../icon.png"
  android: true
  ios: true
  linux: true
  web: true
  remove_alpha_ios: true

flutter:
  assets:
    - sport-log-client.yaml
    - assets/audio/beep_long.mp3
    - assets/audio/beep_short.mp3

  uses-material-design: true

  fonts:
   - family:  CustomIcons
     fonts:
      - asset: assets/fonts/CustomIcons.ttf
