#[macro_use]
extern crate rocket;

use sport_log_types::types::{Db, CONFIG};

mod handler;

const BASE: &str = "/v1";

#[launch]
fn rocket() -> _ {
    dotenv::dotenv().ok();

    lazy_static::initialize(&CONFIG);

    use handler::*;
    rocket::build().attach(Db::fairing()).mount(
        BASE,
        routes![
            user::adm_create_user,
            user::create_user,
            user::get_user,
            user::update_user,
            user::delete_user,
            platform::adm_create_platform,
            platform::adm_get_platforms,
            platform::get_platforms,
            platform::adm_update_platform,
            platform::adm_delete_platform,
            platform::create_platform_credentials,
            platform::get_own_platform_credentials,
            platform::get_own_platform_credentials_by_platform,
            platform::update_platform_credentials,
            platform::delete_platform_credentials,
            action::adm_create_action_provider,
            action::adm_get_action_providers,
            action::adm_delete_action_provider,
            action::ap_create_action,
            action::ap_get_action,
            action::ap_get_actions_by_action_provider,
            action::get_actions,
            action::ap_delete_action,
            action::create_action_rule,
            action::get_action_rule,
            action::get_action_rules_by_user,
            action::get_action_rules_by_user_and_action_provider,
            action::update_action_rule,
            action::delete_action_rule,
            action::create_action_event,
            action::get_action_event,
            action::get_action_events_by_user,
            action::ap_get_action_events_by_action_provider,
            action::get_action_events_by_user_and_action_provider,
            action::update_action_event,
            action::delete_action_event,
            action::ap_delete_action_event,
            action::ap_get_executable_action_events_by_action_provider,
            action::ap_get_ordered_executable_action_events_by_action_provider_and_timespan,
            diary_wod::create_wod,
            diary_wod::ap_create_wod,
            diary_wod::get_wods_by_user,
            diary_wod::update_wod,
            diary_wod::delete_wod,
            diary_wod::create_diary,
            diary_wod::get_diary,
            diary_wod::get_diarys_by_user,
            diary_wod::update_diary,
            diary_wod::delete_diary,
            movement::create_movement,
            movement::get_movement,
            movement::get_movements_by_user,
            movement::update_movement,
            movement::delete_movement,
            movement::get_eorms,
            strength::create_strength_session,
            strength::get_strength_session,
            strength::get_strength_sessions_by_user,
            strength::update_strength_session,
            strength::delete_strength_session,
            strength::create_strength_set,
            strength::get_strength_set,
            strength::get_strength_sets_by_strength_session,
            strength::update_strength_set,
            strength::delete_strength_set,
            strength::get_strength_session_description,
            strength::get_strength_session_descriptions_by_user,
            strength::get_ordered_strength_session_descriptions_by_user_and_timespan,
            metcon::create_metcon,
            metcon::get_metcon,
            metcon::get_metcons_by_user,
            metcon::update_metcon,
            metcon::delete_metcon,
            metcon::create_metcon_movement,
            metcon::get_metcon_movement,
            metcon::get_metcon_movements_by_metcon,
            metcon::update_metcon_movement,
            metcon::delete_metcon_movement,
            metcon::get_metcon_session_description,
            metcon::get_metcon_session_descriptions_by_user,
            metcon::get_ordered_metcon_session_descriptions_by_user_and_timespan,
            cardio::create_route,
            cardio::get_route,
            cardio::get_routes_by_user,
            cardio::update_route,
            cardio::delete_route,
            cardio::create_cardio_session,
            cardio::get_cardio_session,
            cardio::get_cardio_sessions_by_user,
            cardio::update_cardio_session,
            cardio::delete_cardio_session,
            cardio::get_cardio_session_description,
            cardio::get_cardio_session_descriptions_by_user,
            cardio::get_ordered_cardio_session_descriptions_by_user_and_timespan,
            activity::get_activities_ordered_by_user_and_timespan,
            account::get_account_data_by_user,
        ],
    )
}
