name: Flutter

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - name: Format
      working-directory: sport-log-client
      run: flutter format --set-exit-if-changed .

  analyze:
    name: "Analize"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - name: Get Dependencies
      working-directory: sport-log-client
      run: flutter pub get
    - name: Analyze
      working-directory: sport-log-client
      run: flutter analyze

  build-android:
    name: "Build Android"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - name: Get Dependencies
      working-directory: sport-log-client
      run: flutter pub get
    - name: Build APK
      working-directory: sport-log-client
      run: flutter build apk
      env:
        SDK_REGISTRY_TOKEN: ${{ secrets.SDK_REGISTRY_TOKEN }}
