name: Flutter

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  format:
    name: "Flutter: Check Formatting"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - name: Format
      working-directory: sport-log-client
      run: flutter format --set-exit-if-changed .

  analyze:
    name: "Flutter: Analize"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - name: Get Dependencies
      working-directory: sport-log-client
      run: |
        cp sport-log-client.yaml.template sport-log-client.yaml
        flutter pub get
    - name: Analyze
      working-directory: sport-log-client
      run: flutter analyze

  build-android:
    name: "Flutter: Build Android"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - name: Get Dependencies
      working-directory: sport-log-client
      run: flutter pub get
    - name: Build APK
      working-directory: sport-log-client
      run: |
        cp sport-log-client.yaml.template sport-log-client.yaml
        flutter build apk --release --flavor production
      env:
        SDK_REGISTRY_TOKEN: ${{ secrets.SDK_REGISTRY_TOKEN }}

  build-linux:
    name: "Flutter: Build Linux"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - name: Setup Linux Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
    - name: Enable Linux Build
      run: flutter config --enable-linux-desktop
    - name: Build Linux
      working-directory: sport-log-client
      run: |
        cp sport-log-client.yaml.template sport-log-client.yaml
        flutter build linux --release
      env:
        SDK_REGISTRY_TOKEN: ${{ secrets.SDK_REGISTRY_TOKEN }}
    - name: Setup Flatpak
      run: |
        sudo apt-get update -y
        sudo apt-get install -y flatpak flatpak-builder
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install --user -y flathub org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08
    - name: Build Flatpak
      working-directory: sport-log-client
      run: flatpak-builder --user --install --force-clean --state-dir ../.flatpak-builder ../flatpak-build flatpak/org.sport-log.sport-log-client.yml