name: Flutter

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format:
    name: format
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
    - name: dart format
      working-directory: sport-log-client
      run: dart format --set-exit-if-changed .

  analyze:
    name: analyze
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
    - name: flutter pub get
      working-directory: sport-log-client
      run: |
        cp sport-log-client.yaml.template sport-log-client.yaml
        flutter pub get
    - name: flutter analyze
      working-directory: sport-log-client
      run: flutter analyze
    #- name: dart run dart_code_linter
      #working-directory: sport-log-client
      #run: dart run dart_code_linter:metrics analyze --set-exit-on-violation-level=warning lib

  codegen:
    name: codegen
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
    - name: flutter pub get
      working-directory: sport-log-client
      run: flutter pub get
    - name: codegen
      working-directory: sport-log-client
      run: |
        dart run build_runner build --delete-conflicting-outputs
        git diff --exit-code

  build-android:
    name: build android
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
    - name: flutter pub get
      working-directory: sport-log-client
      run: flutter pub get
    - name: flutter build apk
      working-directory: sport-log-client
      run: |
        cp sport-log-client.yaml.template sport-log-client.yaml
        flutter build apk --debug \
            --flavor production \
            --target-platform android-arm64 \
            --split-per-abi \
            --dart-define GIT_REF=$(git show-ref --head --hash=7 HEAD)

  build-linux:
    name: build linux
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
    - name: install linux dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
        sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
    - name: enable linux build
      run: flutter config --enable-linux-desktop
    - name: flutter pub get
      working-directory: sport-log-client
      run: flutter pub get
    - name: flutter build linux
      working-directory: sport-log-client
      run: |
        cp sport-log-client.yaml.template sport-log-client.yaml
        flutter build linux --release
    - name: install and setup flatpak
      run: |
        sudo apt-get update -y
        sudo apt-get install -y flatpak flatpak-builder
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install --user -y flathub org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08
    - name: build flatpak
      working-directory: sport-log-client
      run: flatpak-builder --user --install --force-clean --state-dir ../.flatpak-builder ../flatpak-build flatpak/org.sport-log.sport-log-client.yml