name: Flutter

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
    - name: get dependencies
      run: flutter pub get
      working-directory: sport-log-client
    - name: format
      run: flutter format --set-exit-if-changed .
      working-directory: sport-log-client
    # - name: analyze
      # run: flutter analyze
      # working-directory: sport-log-client
    # - name: test
      # run: flutter test
      # working-directory: sport-log-client
    # - name: build # needs SDK_REGISTRY_TOKEN as env arg
      # run: flutter build apk
      # working-directory: sport-log-client
