name: Rust

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo check --manifest-path sport-log-action-provider-map-matcher/Cargo.toml &&
           cargo check --manifest-path sport-log-action-provider-sportstracker/Cargo.toml &&
           cargo check --manifest-path sport-log-action-provider-wodify-login/Cargo.toml &&
           cargo check --manifest-path sport-log-action-provider-wodify-wod/Cargo.toml &&
           cargo check --manifest-path sport-log-ap-utils/Cargo.toml &&
           cargo check --manifest-path sport-log-api-tester/Cargo.toml &&
           cargo check --manifest-path sport-log-password-hasher/Cargo.toml &&
           cargo check --manifest-path sport-log-scheduler/Cargo.toml &&
           cargo check --manifest-path sport-log-server/Cargo.toml &&
           cargo check --manifest-path sport-log-types/Cargo.toml &&
           cargo check --manifest-path sport-log-types-derive/Cargo.toml
    #- name: Run tests
    #  run: cargo test --verbose
  
  style:
    name: Check style
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt

    - name: Cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  clippy:
    name: Run clippy
    needs: [style]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy

    - name: Cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets -- -D warnings
