name: Rust

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: format
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt
    - name: cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: cargo clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
    
  doc:
    name: doc
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: load cache
      uses: Swatinem/rust-cache@v1
    - name: cargo doc
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-deps --all-features

  build:
    name: check
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: load cache
      uses: Swatinem/rust-cache@v1
    - name: cargo check
      # build every crate on its own to make sure enabled features from other crates do not mask missing dependencies
      run: cargo check --manifest-path sport-log-action-provider-sportstracker/Cargo.toml &&
           cargo check --manifest-path sport-log-action-provider-wodify-login/Cargo.toml &&
           cargo check --manifest-path sport-log-action-provider-wodify-wod/Cargo.toml &&
           cargo check --manifest-path sport-log-ap-utils/Cargo.toml &&
           cargo check --manifest-path sport-log-scheduler/Cargo.toml &&
           cargo check --manifest-path sport-log-server/Cargo.toml &&
           cargo check --manifest-path sport-log-types/Cargo.toml &&
           cargo check --manifest-path sport-log-types-derive/Cargo.toml &&
           cargo check --tests

    #- name: Run tests
    #  run: cargo test --verbose

  deps:
    name: unused deps
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install cargo-machete
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-machete
        version: latest
    - name: cargo machete
      run: cargo machete
