name: Rust

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: format
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: cargo fmt
      run: cargo fmt --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: cargo clippy
      run: cargo clippy --all-features
    
  doc:
    name: doc
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install rust
      uses: dtolnay/rust-toolchain@stable
    - name: load cache
      uses: Swatinem/rust-cache@v2
    - name: cargo doc
      run: cargo doc --no-deps --all-features

  build:
    name: check
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install rust
      uses: dtolnay/rust-toolchain@stable
    - name: load cache
      uses: Swatinem/rust-cache@v2
    - name: cargo check
      # build every crate on its own to make sure enabled features from other crates do not mask missing dependencies
      run: cargo check --manifest-path sport-log-action-provider-sportstracker/Cargo.toml &&
           cargo check --manifest-path sport-log-action-provider-wodify-login/Cargo.toml &&
           cargo check --manifest-path sport-log-action-provider-wodify-wod/Cargo.toml &&
           cargo check --manifest-path sport-log-ap-utils/Cargo.toml &&
           cargo check --manifest-path sport-log-scheduler/Cargo.toml &&
           cargo check --manifest-path sport-log-server/Cargo.toml &&
           cargo check --manifest-path sport-log-types/Cargo.toml &&
           cargo check --manifest-path sport-log-types-derive/Cargo.toml

  test:
    name: test
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: sport_log
      POSTGRES_PASSWORD: test-passwd
      POSTGRES_USER: sport_admin

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: sport_log
          POSTGRES_PASSWORD: test-passwd
          POSTGRES_USER: sport_admin
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: env
      run: echo "DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost/$POSTGRES_DB" >> $GITHUB_ENV
    - name: checkout
      uses: actions/checkout@v4
    - name: install rust
      uses: dtolnay/rust-toolchain@stable
    - name: load cache
      uses: Swatinem/rust-cache@v2
    - name: install postgresql
      run: |
        sudo apt-get update -y
        sudo apt-get install libpq-dev postgresql-client-common postgresql
    - name: install diesel_cli
      run: cargo install diesel_cli --no-default-features --features postgres
    - name: setup database
      working-directory: sport-log-types
      run: |
        diesel database setup
        patch src/schema.rs src/schema.patch
      # diesel database setup --locked-schema TODO
    - name: create sport-log-server.toml file
      working-directory: sport-log-server
      env:
        ADMIN_PASSWORD: "$argon2id$v=19$m=4096,t=3,p=1$jfQMFwbuWJW6kYF3K6Opxg$8zmHSEMYeXuxhxl7HNv8/zsgSx/LWm6Iy1EciOBJdQM" # = "admin-passwd"
      run: |
        echo "
        admin_password = \"$ADMIN_PASSWORD\"
        user_self_registration = true
        ap_self_registration = true
        database_url = \"$DATABASE_URL\"
        release_address = \"0.0.0.0:8000\"
        debug_address = \"0.0.0.0:8001\"
        " > sport-log-server.toml
    - name: cargo test
      run: cargo test

  deps:
    name: unused deps
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: load cache
      uses: Swatinem/rust-cache@v2
    - name: install cargo-machete
      run: cargo install cargo-machete
    - name: cargo machete
      run: cargo machete
